// Common emoji shortcodes mapping
export const EMOJI_SHORTCODES: Record<string, string> = {
  // Smileys & Emotion
  ':smile:': '😄',
  ':grin:': '😁',
  ':joy:': '😂',
  ':laughing:': '😆',
  ':grinning:': '😀',
  ':wink:': '😉',
  ':blush:': '😊',
  ':innocent:': '😇',
  ':heart_eyes:': '😍',
  ':kissing_heart:': '😘',
  ':kissing:': '😗',
  ':relaxed:': '☺️',
  ':satisfied:': '😆',
  ':grinning_face_with_big_eyes:': '😃',
  ':smiling_face_with_smiling_eyes:': '😊',
  ':face_with_tears_of_joy:': '😂',
  ':rolling_on_the_floor_laughing:': '🤣',
  ':slightly_smiling_face:': '🙂',
  ':upside_down_face:': '🙃',
  ':melting_face:': '🫠',
  ':thinking:': '🤔',
  ':confused:': '😕',
  ':worried:': '😟',
  ':cry:': '😢',
  ':sob:': '😭',
  ':angry:': '😠',
  ':rage:': '😡',
  ':triumph:': '😤',
  ':sleepy:': '😪',
  ':yawn:': '🥱',
  ':mask:': '😷',
  ':face_with_thermometer:': '🤒',
  ':sunglasses:': '😎',
  ':nerd:': '🤓',
  ':star_struck:': '🤩',
  ':partying_face:': '🥳',
  ':smirk:': '😏',
  ':unamused:': '😒',
  ':disappointed:': '😞',
  ':pensive:': '😔',
  ':fearful:': '😨',
  ':cold_sweat:': '😰',
  ':persevere:': '😣',
  ':confounded:': '😖',
  ':tired_face:': '😫',
  ':weary:': '😩',
  ':pleading_face:': '🥺',
  ':flushed:': '😳',
  ':zany_face:': '🤪',
  ':dizzy_face:': '😵',
  ':exploding_head:': '🤯',
  ':cowboy:': '🤠',
  ':partying:': '🥳',
  ':disguised_face:': '🥸',

  // Gestures & People
  ':thumbsup:': '👍',
  ':thumbsdown:': '👍',
  ':ok_hand:': '👌',
  ':peace:': '✌️',
  ':crossed_fingers:': '🤞',
  ':love_you_gesture:': '🤟',
  ':sign_of_the_horns:': '🤘',
  ':call_me_hand:': '🤙',
  ':point_left:': '👈',
  ':point_right:': '👉',
  ':point_up:': '👆',
  ':point_down:': '👇',
  ':raised_hand:': '✋',
  ':raised_back_of_hand:': '🤚',
  ':vulcan_salute:': '🖖',
  ':wave:': '👋',
  ':clap:': '👏',
  ':raised_hands:': '🙌',
  ':palms_up_together:': '🤲',
  ':handshake:': '🤝',
  ':pray:': '🙏',
  ':facepalm:': '🤦',
  ':shrug:': '🤷',
  ':muscle:': '💪',
  ':leg:': '🦵',
  ':foot:': '🦶',

  // Hearts & Symbols
  ':heart:': '❤️',
  ':orange_heart:': '🧡',
  ':yellow_heart:': '💛',
  ':green_heart:': '💚',
  ':blue_heart:': '💙',
  ':purple_heart:': '💜',
  ':brown_heart:': '🤎',
  ':black_heart:': '🖤',
  ':white_heart:': '🤍',
  ':broken_heart:': '💔',
  ':heart_on_fire:': '❤️‍🔥',
  ':mending_heart:': '❤️‍🩹',
  ':sparkling_heart:': '💖',
  ':revolving_hearts:': '💞',
  ':two_hearts:': '💕',
  ':heartbeat:': '💓',
  ':heartpulse:': '💗',
  ':cupid:': '💘',
  ':gift_heart:': '💝',
  ':kiss:': '💋',
  ':fire:': '🔥',
  ':star:': '⭐',
  ':sparkles:': '✨',
  ':zap:': '⚡',
  ':boom:': '💥',
  ':sweat_drops:': '💦',
  ':dash:': '💨',

  // Nature & Animals
  ':dog:': '🐶',
  ':cat:': '🐱',
  ':mouse:': '🐭',
  ':hamster:': '🐹',
  ':rabbit:': '🐰',
  ':fox:': '🦊',
  ':bear:': '🐻',
  ':panda:': '🐼',
  ':koala:': '🐨',
  ':tiger:': '🐯',
  ':lion:': '🦁',
  ':cow:': '🐮',
  ':pig:': '🐷',
  ':frog:': '🐸',
  ':monkey:': '🐵',
  ':chicken:': '🐔',
  ':penguin:': '🐧',
  ':bird:': '🐦',
  ':duck:': '🦆',
  ':eagle:': '🦅',
  ':owl:': '🦉',
  ':bat:': '🦇',
  ':wolf:': '🐺',
  ':unicorn:': '🦄',
  ':horse:': '🐴',
  ':zebra:': '🦓',
  ':deer:': '🦌',
  ':elephant:': '🐘',
  ':rhino:': '🦏',
  ':hippo:': '🦛',
  ':giraffe:': '🦒',
  ':camel:': '🐪',
  ':kangaroo:': '🦘',
  ':llama:': '🦙',
  ':sloth:': '🦥',
  ':otter:': '🦦',
  ':skunk:': '🦨',
  ':badger:': '🦡',

  // Food & Drink
  ':apple:': '🍎',
  ':orange:': '🍊',
  ':lemon:': '🍋',
  ':lime:': '🍈',
  ':watermelon:': '🍉',
  ':grapes:': '🍇',
  ':strawberry:': '🍓',
  ':melon:': '🍈',
  ':banana:': '🍌',
  ':pineapple:': '🍍',
  ':mango:': '🥭',
  ':peach:': '🍑',
  ':cherries:': '🍒',
  ':tomato:': '🍅',
  ':eggplant:': '🍆',
  ':corn:': '🌽',
  ':hot_pepper:': '🌶️',
  ':cucumber:': '🥒',
  ':leafy_greens:': '🥬',
  ':broccoli:': '🥦',
  ':garlic:': '🧄',
  ':onion:': '🧅',
  ':mushroom:': '🍄',
  ':peanuts:': '🥜',
  ':chestnut:': '🌰',
  ':bread:': '🍞',
  ':croissant:': '🥐',
  ':baguette:': '🥖',
  ':pretzel:': '🥨',
  ':bagel:': '🥯',
  ':pancakes:': '🥞',
  ':waffle:': '🧇',
  ':cheese:': '🧀',
  ':meat_on_bone:': '🍖',
  ':poultry_leg:': '🍗',
  ':cut_of_meat:': '🥩',
  ':bacon:': '🥓',
  ':hamburger:': '🍔',
  ':fries:': '🍟',
  ':pizza:': '🍕',
  ':hotdog:': '🌭',
  ':sandwich:': '🥪',
  ':taco:': '🌮',
  ':burrito:': '🌯',

  // Objects & Symbols
  ':computer:': '💻',
  ':phone:': '📱',
  ':watch:': '⌚',
  ':camera:': '📷',
  ':video_camera:': '📹',
  ':tv:': '📺',
  ':radio:': '📻',
  ':headphones:': '🎧',
  ':microphone:': '🎤',
  ':battery:': '🔋',
  ':electric_plug:': '🔌',
  ':bulb:': '💡',
  ':flashlight:': '🔦',
  ':candle:': '🕯️',
  ':fire_extinguisher:': '🧯',
  ':oil_drum:': '🛢️',
  ':money_with_wings:': '💸',
  ':dollar:': '💵',
  ':yen:': '💴',
  ':euro:': '💶',
  ':pound:': '💷',
  ':coin:': '🪙',
  ':credit_card:': '💳',
  ':gem:': '💎',
  ':scales:': '⚖️',
  ':ladder:': '🪜',
  ':toolbox:': '🧰',
  ':wrench:': '🔧',
  ':hammer:': '🔨',
  ':pick:': '⛏️',
  ':nut_and_bolt:': '🔩',
  ':gear:': '⚙️',
  ':chains:': '⛓️',
  ':gun:': '🔫',
  ':bomb:': '💣',
  ':knife:': '🔪',
  ':dagger:': '🗡️',
  ':shield:': '🛡️',
  ':key:': '🔑',
  ':lock:': '🔒',
  ':unlock:': '🔓',

  // Miscellaneous popular ones
  ':100:': '💯',
  ':rocket:': '🚀',
  ':airplane:': '✈️',
  ':car:': '🚗',
  ':bike:': '🚲',
  ':train:': '🚂',
  ':bus:': '🚌',
  ':ship:': '🚢',
  ':anchor:': '⚓',
  ':house:': '🏠',
  ':office:': '🏢',
  ':hospital:': '🏥',
  ':school:': '🏫',
  ':factory:': '🏭',
  ':castle:': '🏰',
  ':rainbow:': '🌈',
  ':sun:': '☀️',
  ':cloud:': '☁️',
  ':umbrella:': '☂️',
  ':snowman:': '⛄',
  ':moon:': '🌙',
  ':star2:': '🌟',
  ':comet:': '☄️',
  ':earth_africa:': '🌍',
  ':earth_americas:': '🌎',
  ':earth_asia:': '🌏'
}

// Get all shortcode keys for autocomplete
export const getAllShortcodes = (): string[] => {
  return Object.keys(EMOJI_SHORTCODES)
}

// Convert shortcode to emoji
export const shortcodeToEmoji = (shortcode: string): string | null => {
  return EMOJI_SHORTCODES[shortcode] || null
}

// Find shortcodes that match a partial input
export const findMatchingShortcodes = (partial: string): string[] => {
  if (!partial.startsWith(':')) return []
  
  return Object.keys(EMOJI_SHORTCODES)
    .filter(shortcode => shortcode.startsWith(partial))
    .slice(0, 10) // Limit to 10 suggestions
}

// Replace shortcodes in text with emojis
export const replaceShortcodesInText = (text: string): string => {
  let result = text
  
  // Find all :shortcode: patterns
  const shortcodePattern = /:([a-zA-Z0-9_]+):/g
  
  result = result.replace(shortcodePattern, (match) => {
    const emoji = EMOJI_SHORTCODES[match]
    return emoji || match // Return emoji if found, otherwise keep original
  })
  
  return result
}